// Generated by build-music.cjs. Times include trimming and every crossfade.
window.WALTZ_SCORE = {
  "bpm": 150,
  "beat": 0.4,
  "duration": 63,
  "overlap": 0,
  "sourceBeats": [
    0.02,
    0.41,
    0.81,
    1.22,
    1.61,
    2.01,
    2.43,
    2.81,
    3.21,
    3.65,
    4.01,
    4.41,
    4.82,
    5.2,
    5.61,
    6.02,
    6.41,
    6.81,
    7.22,
    7.61,
    8.01,
    8.42
  ],
  "basis": "upper-register-melody-onsets",
  "melodyEvents": [
    {
      "time": 0.02,
      "pitch": 76,
      "strength": 186.09,
      "pitchChange": false
    },
    {
      "time": 0.41,
      "pitch": 88,
      "strength": 393.08,
      "pitchChange": true
    },
    {
      "time": 0.61,
      "pitch": 87,
      "strength": 108.77,
      "pitchChange": true
    },
    {
      "time": 0.81,
      "pitch": 83,
      "strength": 432.54,
      "pitchChange": true
    },
    {
      "time": 1.01,
      "pitch": 87,
      "strength": 115.8,
      "pitchChange": true
    },
    {
      "time": 1.26,
      "pitch": 76,
      "strength": 210.1,
      "pitchChange": false
    },
    {
      "time": 1.61,
      "pitch": 76,
      "strength": 394.31,
      "pitchChange": false
    },
    {
      "time": 2.01,
      "pitch": 79,
      "strength": 488.25,
      "pitchChange": false
    },
    {
      "time": 2.41,
      "pitch": 85,
      "strength": 127.62,
      "pitchChange": true
    },
    {
      "time": 2.82,
      "pitch": 73,
      "strength": 363.4,
      "pitchChange": true
    },
    {
      "time": 3,
      "pitch": 84,
      "strength": 92.59,
      "pitchChange": true
    },
    {
      "time": 3.21,
      "pitch": 73,
      "strength": 394.01,
      "pitchChange": true
    },
    {
      "time": 3.41,
      "pitch": 88,
      "strength": 99.58,
      "pitchChange": true
    },
    {
      "time": 3.63,
      "pitch": 86,
      "strength": 184.91,
      "pitchChange": true
    },
    {
      "time": 4.02,
      "pitch": 81,
      "strength": 376.87,
      "pitchChange": true
    },
    {
      "time": 4.42,
      "pitch": 81,
      "strength": 398.43,
      "pitchChange": true
    },
    {
      "time": 4.83,
      "pitch": 83,
      "strength": 166,
      "pitchChange": false
    },
    {
      "time": 5.21,
      "pitch": 90,
      "strength": 405.08,
      "pitchChange": false
    },
    {
      "time": 5.41,
      "pitch": 84,
      "strength": 100.97,
      "pitchChange": true
    },
    {
      "time": 5.61,
      "pitch": 74,
      "strength": 500.28,
      "pitchChange": true
    },
    {
      "time": 5.82,
      "pitch": 86,
      "strength": 118.37,
      "pitchChange": false
    },
    {
      "time": 6.02,
      "pitch": 88,
      "strength": 214.03,
      "pitchChange": false
    },
    {
      "time": 6.41,
      "pitch": 74,
      "strength": 409.23,
      "pitchChange": true
    },
    {
      "time": 6.81,
      "pitch": 83,
      "strength": 402.97,
      "pitchChange": true
    },
    {
      "time": 7.24,
      "pitch": 86,
      "strength": 172.96,
      "pitchChange": false
    },
    {
      "time": 7.63,
      "pitch": 88,
      "strength": 386.97,
      "pitchChange": true
    },
    {
      "time": 8.02,
      "pitch": 88,
      "strength": 400.5,
      "pitchChange": false
    },
    {
      "time": 8.42,
      "pitch": 76,
      "strength": 433.5,
      "pitchChange": true
    }
  ],
  "cycle": 9,
  "notes": [
    {
      "time": 0.02,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 0.41,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 0.81,
      "lane": 0,
      "pitch": 83
    },
    {
      "time": 1.61,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 2.01,
      "lane": 1,
      "pitch": 79
    },
    {
      "time": 3.21,
      "lane": 0,
      "pitch": 73
    },
    {
      "time": 4.42,
      "lane": 1,
      "pitch": 81
    },
    {
      "time": 5.21,
      "lane": 1,
      "pitch": 90
    },
    {
      "time": 5.61,
      "lane": 0,
      "pitch": 74
    },
    {
      "time": 6.41,
      "lane": 1,
      "pitch": 74
    },
    {
      "time": 6.81,
      "lane": 1,
      "pitch": 83
    },
    {
      "time": 8.02,
      "lane": 0,
      "pitch": 88
    },
    {
      "time": 8.42,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 9.02,
      "lane": 1,
      "pitch": 76
    },
    {
      "time": 9.41,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 9.81,
      "lane": 0,
      "pitch": 83
    },
    {
      "time": 10.61,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 11.01,
      "lane": 1,
      "pitch": 79
    },
    {
      "time": 11.82,
      "lane": 0,
      "pitch": 73
    },
    {
      "time": 12.21,
      "lane": 1,
      "pitch": 73
    },
    {
      "time": 13.02,
      "lane": 1,
      "pitch": 81
    },
    {
      "time": 13.42,
      "lane": 0,
      "pitch": 81
    },
    {
      "time": 14.21,
      "lane": 1,
      "pitch": 90
    },
    {
      "time": 14.61,
      "lane": 0,
      "pitch": 74
    },
    {
      "time": 15.02,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 15.41,
      "lane": 0,
      "pitch": 74
    },
    {
      "time": 15.81,
      "lane": 1,
      "pitch": 83
    },
    {
      "time": 16.63,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 17.02,
      "lane": 0,
      "pitch": 88
    },
    {
      "time": 17.42,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 18.02,
      "lane": 1,
      "pitch": 76
    },
    {
      "time": 18.41,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 18.81,
      "lane": 0,
      "pitch": 83
    },
    {
      "time": 19.26,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 19.61,
      "lane": 1,
      "pitch": 76
    },
    {
      "time": 20.01,
      "lane": 1,
      "pitch": 79
    },
    {
      "time": 20.82,
      "lane": 0,
      "pitch": 73
    },
    {
      "time": 21.21,
      "lane": 1,
      "pitch": 73
    },
    {
      "time": 21.63,
      "lane": 1,
      "pitch": 86
    },
    {
      "time": 22.02,
      "lane": 0,
      "pitch": 81
    },
    {
      "time": 22.42,
      "lane": 1,
      "pitch": 81
    },
    {
      "time": 23.21,
      "lane": 1,
      "pitch": 90
    },
    {
      "time": 23.61,
      "lane": 0,
      "pitch": 74
    },
    {
      "time": 24.02,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 24.41,
      "lane": 0,
      "pitch": 74
    },
    {
      "time": 24.81,
      "lane": 1,
      "pitch": 83
    },
    {
      "time": 25.24,
      "lane": 1,
      "pitch": 86
    },
    {
      "time": 25.63,
      "lane": 0,
      "pitch": 88
    },
    {
      "time": 26.02,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 26.42,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 27.02,
      "lane": 1,
      "pitch": 76
    },
    {
      "time": 27.41,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 27.81,
      "lane": 0,
      "pitch": 83
    },
    {
      "time": 28.26,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 28.61,
      "lane": 1,
      "pitch": 76
    },
    {
      "time": 29.01,
      "lane": 1,
      "pitch": 79
    },
    {
      "time": 29.41,
      "lane": 0,
      "pitch": 85
    },
    {
      "time": 29.82,
      "lane": 0,
      "pitch": 73
    },
    {
      "time": 30.21,
      "lane": 1,
      "pitch": 73
    },
    {
      "time": 30.63,
      "lane": 1,
      "pitch": 86
    },
    {
      "time": 31.02,
      "lane": 0,
      "pitch": 81
    },
    {
      "time": 31.42,
      "lane": 1,
      "pitch": 81
    },
    {
      "time": 31.83,
      "lane": 1,
      "pitch": 83
    },
    {
      "time": 32.21,
      "lane": 0,
      "pitch": 90
    },
    {
      "time": 32.61,
      "lane": 0,
      "pitch": 74
    },
    {
      "time": 33.02,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 33.41,
      "lane": 0,
      "pitch": 74
    },
    {
      "time": 33.81,
      "lane": 1,
      "pitch": 83
    },
    {
      "time": 34.24,
      "lane": 1,
      "pitch": 86
    },
    {
      "time": 34.63,
      "lane": 0,
      "pitch": 88
    },
    {
      "time": 35.02,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 35.42,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 36.02,
      "lane": 1,
      "pitch": 76
    },
    {
      "time": 36.41,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 36.81,
      "lane": 0,
      "pitch": 83
    },
    {
      "time": 37.01,
      "lane": 1,
      "pitch": 87
    },
    {
      "time": 37.26,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 37.61,
      "lane": 1,
      "pitch": 76
    },
    {
      "time": 38.01,
      "lane": 1,
      "pitch": 79
    },
    {
      "time": 38.41,
      "lane": 0,
      "pitch": 85
    },
    {
      "time": 38.82,
      "lane": 0,
      "pitch": 73
    },
    {
      "time": 39.21,
      "lane": 1,
      "pitch": 73
    },
    {
      "time": 39.63,
      "lane": 1,
      "pitch": 86
    },
    {
      "time": 40.02,
      "lane": 0,
      "pitch": 81
    },
    {
      "time": 40.42,
      "lane": 1,
      "pitch": 81
    },
    {
      "time": 40.83,
      "lane": 1,
      "pitch": 83
    },
    {
      "time": 41.21,
      "lane": 0,
      "pitch": 90
    },
    {
      "time": 41.61,
      "lane": 0,
      "pitch": 74
    },
    {
      "time": 41.82,
      "lane": 1,
      "pitch": 86
    },
    {
      "time": 42.02,
      "lane": 0,
      "pitch": 88
    },
    {
      "time": 42.41,
      "lane": 0,
      "pitch": 74
    },
    {
      "time": 42.81,
      "lane": 1,
      "pitch": 83
    },
    {
      "time": 43.24,
      "lane": 1,
      "pitch": 86
    },
    {
      "time": 43.63,
      "lane": 0,
      "pitch": 88
    },
    {
      "time": 44.02,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 44.42,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 45.02,
      "lane": 1,
      "pitch": 76
    },
    {
      "time": 45.41,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 45.61,
      "lane": 0,
      "pitch": 87
    },
    {
      "time": 45.81,
      "lane": 1,
      "pitch": 83
    },
    {
      "time": 46.01,
      "lane": 0,
      "pitch": 87
    },
    {
      "time": 46.26,
      "lane": 1,
      "pitch": 76
    },
    {
      "time": 46.61,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 47.01,
      "lane": 1,
      "pitch": 79
    },
    {
      "time": 47.41,
      "lane": 1,
      "pitch": 85
    },
    {
      "time": 47.82,
      "lane": 0,
      "pitch": 73
    },
    {
      "time": 48.21,
      "lane": 1,
      "pitch": 73
    },
    {
      "time": 48.63,
      "lane": 1,
      "pitch": 86
    },
    {
      "time": 49.02,
      "lane": 0,
      "pitch": 81
    },
    {
      "time": 49.42,
      "lane": 1,
      "pitch": 81
    },
    {
      "time": 49.83,
      "lane": 1,
      "pitch": 83
    },
    {
      "time": 50.21,
      "lane": 0,
      "pitch": 90
    },
    {
      "time": 50.41,
      "lane": 1,
      "pitch": 84
    },
    {
      "time": 50.61,
      "lane": 0,
      "pitch": 74
    },
    {
      "time": 50.82,
      "lane": 1,
      "pitch": 86
    },
    {
      "time": 51.02,
      "lane": 0,
      "pitch": 88
    },
    {
      "time": 51.41,
      "lane": 0,
      "pitch": 74
    },
    {
      "time": 51.81,
      "lane": 1,
      "pitch": 83
    },
    {
      "time": 52.24,
      "lane": 1,
      "pitch": 86
    },
    {
      "time": 52.63,
      "lane": 0,
      "pitch": 88
    },
    {
      "time": 53.02,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 53.42,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 54.02,
      "lane": 1,
      "pitch": 76
    },
    {
      "time": 54.41,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 54.61,
      "lane": 0,
      "pitch": 87
    },
    {
      "time": 54.81,
      "lane": 1,
      "pitch": 83
    },
    {
      "time": 55.01,
      "lane": 0,
      "pitch": 87
    },
    {
      "time": 55.26,
      "lane": 1,
      "pitch": 76
    },
    {
      "time": 55.61,
      "lane": 0,
      "pitch": 76
    },
    {
      "time": 56.01,
      "lane": 1,
      "pitch": 79
    },
    {
      "time": 56.41,
      "lane": 1,
      "pitch": 85
    },
    {
      "time": 56.82,
      "lane": 0,
      "pitch": 73
    },
    {
      "time": 57,
      "lane": 1,
      "pitch": 84
    },
    {
      "time": 57.21,
      "lane": 0,
      "pitch": 73
    },
    {
      "time": 57.41,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 57.63,
      "lane": 0,
      "pitch": 86
    },
    {
      "time": 58.02,
      "lane": 0,
      "pitch": 81
    },
    {
      "time": 58.42,
      "lane": 1,
      "pitch": 81
    },
    {
      "time": 58.83,
      "lane": 1,
      "pitch": 83
    },
    {
      "time": 59.21,
      "lane": 0,
      "pitch": 90
    },
    {
      "time": 59.41,
      "lane": 1,
      "pitch": 84
    },
    {
      "time": 59.61,
      "lane": 0,
      "pitch": 74
    },
    {
      "time": 59.82,
      "lane": 1,
      "pitch": 86
    },
    {
      "time": 60.02,
      "lane": 0,
      "pitch": 88
    },
    {
      "time": 60.41,
      "lane": 0,
      "pitch": 74
    },
    {
      "time": 60.81,
      "lane": 1,
      "pitch": 83
    },
    {
      "time": 61.24,
      "lane": 1,
      "pitch": 86
    },
    {
      "time": 61.63,
      "lane": 0,
      "pitch": 88
    },
    {
      "time": 62.02,
      "lane": 1,
      "pitch": 88
    },
    {
      "time": 62.42,
      "lane": 0,
      "pitch": 76
    }
  ]
};
